version: "3.9"
services:
backend:
build:
context: .
dockerfile: docker/backend.Dockerfile
env_file:

.env
ports:

"8000:8000"
depends_on:

mongo

redis

frontend:
build:
context: .
dockerfile: docker/frontend.Dockerfile
environment:
- VITE_API_BASE=http://localhost:8000/api
ports:
- "5173:5173"
depends_on:
- backend

mongo:
image: mongo:7
restart: always
ports:
- "27017:27017"
volumes:
- mongo_data:/data/db

redis:
image: redis:7
restart: always
ports:
- "6379:6379"

volumes:
mongo_data: